name: Karakeep
version: "0.26.0-v0"
slug: karakeep
codenotary: info@fabiogaravini.dev
description: bookmark-everything app with a touch of AI for the data hoarders out there
url: https://karakeep.app/
webui: http://[HOST]:[PORT:3000]
arch:
  - aarch64
  - amd64
init: false
hassio_api: true
map:
  - type: share
    read_only: false
  - type: ssl
backup: cold
backup_exclude:
  - "**/logs"
schema:
  TZ: str?
  DISABLE_SIGNUPS: bool
  NEXTAUTH_SECRET: password
  MAX_ASSET_SIZE_MB: int?
  NEXTAUTH_URL: str?
  OCR_LANGS: str?
  OCR_CONFIDENCE_THRESHOLD: int(0,100)?
  OPENAI_BASE_URL: str?
  OPENAI_API_KEY: password?
  OLLAMA_BASE_URL: str?
  INFERENCE_TEXT_MODEL: str?
  INFERENCE_IMAGE_MODEL: str?
  EMBEDDING_TEXT_MODEL: str?
  INFERENCE_CONTEXT_LENGTH: int(0,)?
  INFERENCE_LANG: str?
  INFERENCE_JOB_TIMEOUT_SEC: int(0,)?
  CRAWLER_DOWNLOAD_BANNER_IMAGE: bool
  CRAWLER_STORE_SCREENSHOT: bool
  CRAWLER_FULL_PAGE_SCREENSHOT: bool
  CRAWLER_FULL_PAGE_ARCHIVE: bool
  CRAWLER_JOB_TIMEOUT_SEC: int(0,)?
  CRAWLER_NAVIGATE_TIMEOUT_SEC: int(0,)?
  CRAWLER_VIDEO_DOWNLOAD: bool?
  CRAWLER_VIDEO_DOWNLOAD_MAX_SIZE: int?
  CRAWLER_VIDEO_DOWNLOAD_TIMEOUT_SEC: int(0,)?
  CRAWLER_ENABLE_ADBLOCKER: bool

  SMTP_HOST: str?
  SMTP_PORT: int?
  SMTP_SECURE: bool?
  SMTP_USER: str?
  SMTP_PASSWORD: password?
  SMTP_FROM: str?
  OAUTH_WELLKNOWN_URL: str?
  OAUTH_CLIENT_SECRET: password?
  OAUTH_CLIENT_ID: str?
  OAUTH_PROVIDER_NAME: str?
  OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: bool?
  DISABLE_PASSWORD_AUTH: bool?
  
options:
  TZ: Asia/Kolkata
  DISABLE_SIGNUPS: false
  NEXTAUTH_SECRET: "jnE2An0WyIKZvO+WgKJrn8WPW+c3DzV+c9ntBp8CdobTOmpJ"
  MAX_ASSET_SIZE_MB: 4
  CRAWLER_DOWNLOAD_BANNER_IMAGE: true
  CRAWLER_STORE_SCREENSHOT: false
  CRAWLER_FULL_PAGE_SCREENSHOT: false
  CRAWLER_FULL_PAGE_ARCHIVE: false
  CRAWLER_ENABLE_ADBLOCKER: true
  SMTP_HOST:
  SMTP_PORT: 
  SMTP_SECURE: false
  SMTP_USER: 
  SMTP_PASSWORD:
  SMTP_FROM: 
  OAUTH_WELLKNOWN_URL:
  OAUTH_CLIENT_SECRET:
  OAUTH_CLIENT_ID: 
  OAUTH_PROVIDER_NAME: 
  OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: true
  NEXTAUTH_URL:
  DISABLE_PASSWORD_AUTH: true

ports:
  3000/tcp: 50001
ports_description:
  3000/tcp: Web UI
image: fabioogaravini/hassio-{arch}-karakeep
